INSERT INTO BRAND (NAME, DESCRIPTION) VALUES ('BMW', 'GERMAN PREMIUM BRAND');
INSERT INTO BRAND (NAME, DESCRIPTION) VALUES ('Saab', 'Legacy swedish odd car');
INSERT INTO BRAND (NAME, DESCRIPTION) VALUES ('Volvo', 'Safty first');
INSERT INTO BRAND (NAME, DESCRIPTION) VALUES ('Koeningsegg', 'Sports car');
INSERT INTO BRAND (NAME, DESCRIPTION) VALUES ('Audi', 'Family car');
INSERT INTO BRAND (NAME, DESCRIPTION) VALUES ('FIAT', 'Classic Italian Car');

INSERT INTO CARMODEL (NAME, DESCRIPTION, BRANDID) VALUES ('9-5', 'Family size', 2);
INSERT INTO CARMODEL (NAME, DESCRIPTION, BRANDID) VALUES ('V70', 'Combi', 3);
INSERT INTO CARMODEL (NAME, DESCRIPTION, BRANDID) VALUES ('1', 'Sportser', 4);
INSERT INTO CARMODEL (NAME, DESCRIPTION, BRANDID) VALUES ('320', 'Mid size', 1);
INSERT INTO CARMODEL (NAME, DESCRIPTION, BRANDID) VALUES ('A4', 'Big car', 5);
INSERT INTO CARMODEL (NAME, DESCRIPTION, BRANDID) VALUES ('500', 'Mini size', 6);


INSERT INTO CARSTOCK (CARMODELID, MILES, YEAR, PRICE, DESCRIPTION, PICTUREURL, SOLD)
VALUES (1, 10000, 1999, 7000, 'Soltak, automat', 'http://lh4.ggpht.com/-C41mB8UNUAs/UPCxFdbGQWI/AAAAAAAAlcg/TpktfNFbgDc/s1600/2004-saab-9-5-sedan-00011.jpg', FALSE);
INSERT INTO CARSTOCK (CARMODELID, MILES, YEAR, PRICE, DESCRIPTION, PICTUREURL, SOLD)
VALUES (2, 8000, 2012, 95000, 'En ägare', 'http://st.motortrend.com/uploads/sites/10/2015/11/2009-volvo-v70-3.2-wagon-side-view.png', FALSE);
INSERT INTO CARSTOCK (CARMODELID, MILES, YEAR, PRICE, DESCRIPTION, PICTUREURL, SOLD)
VALUES (3, 2000, 2018, 700000, 'Unik!', 'http://i0.wp.com/www.koenigsegg.com/wp-content/uploads/2014/11/DSC_2422.jpg', FALSE);
INSERT INTO CARSTOCK (CARMODELID, MILES, YEAR, PRICE, DESCRIPTION, PICTUREURL, SOLD)
VALUES (4, 10000, 2001, 8000, 'Rostig', 'https://imgsvrcars-a.akamaihd.net/images/2017/3/BMW-320d-GT/x.jpg/BMW-320dGT-8.jpg', FALSE);
INSERT INTO CARSTOCK (CARMODELID, MILES, YEAR, PRICE, DESCRIPTION, PICTUREURL, SOLD)
VALUES (5, 10000, 1999, 7000, 'Fint skick', 'https://images.hgmsites.net/hug/2019-audi-a6_100678998_h.jpg', FALSE);
INSERT INTO CARSTOCK (CARMODELID, MILES, YEAR, PRICE, DESCRIPTION, PICTUREURL, SOLD)
VALUES (6, 3000, 2016, 150000, 'Ferarri-röd', 'https://smgmedia.blob.core.windows.net/images/128968/1024/fiat-500-convertible-ede2d53127d0.jpg', FALSE);

