CREATE TABLE BRAND (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL,
  DESCRIPTION VARCHAR(2000)
 );

CREATE TABLE CARMODEL(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(64),
  DESCRIPTION VARCHAR(2000),
  BRANDID BIGINT
);

CREATE TABLE CARSTOCK(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CARMODELID BIGINT NOT NULL,
  MILES BIGINT NOT NULL,
  YEAR BIGINT NOT NULL,
  PRICE BIGINT,
  DESCRIPTION VARCHAR(2000),
  PICTUREURL VARCHAR(2000),
  SOLD BOOLEAN
);



CREATE TABLE CUSTOMER(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(2000),
  EMAIL VARCHAR(500),
  ADDRESS VARCHAR(500),
  ADDRESS2 VARCHAR(500),
  ZIPCODE VARCHAR(500),
  CITY VARCHAR(500),
  COUNTRY VARCHAR(500)
);

CREATE TABLE PURCHASE(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CUSTOMERID BIGINT NOT NULL,
  CARSTOCKID BIGINT NOT NULL,
  PURCHASEDATE DATE NOT NULL,
  PAIDAMOUNT BIGINT,
  FINALPRICE BIGINT,
  DELIVERYDATE DATE,
  DELIVERED BOOLEAN
  );

ALTER TABLE CARMODEL ADD FOREIGN KEY (BRANDID) REFERENCES BRAND(ID);
ALTER TABLE CARSTOCK ADD FOREIGN KEY (CARMODELID) REFERENCES CARMODEL(ID);
ALTER TABLE PURCHASE ADD FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(ID);
ALTER TABLE PURCHASE ADD FOREIGN KEY (CARSTOCKID) REFERENCES CARSTOCK(ID);
